version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=web
      - POSTGRES_DB=web
      - POSTGRES_PASSWORD

volumes:
  db-data:
    driver: local
